name: eni_auth
description: "A flexible authentication framework for Flutter applications supporting OAuth2, secure credential storage, and cross-platform authentication flows for web and desktop."
version: 2.0.5
homepage: https://eniware-systems.de
publish_to: https://gitea.eniware-systems.de/api/packages/eni-flutter/pub

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter

  eni_svc:
    git:
      url: https://github.com/eniware-systems/eni_svc.git
      ref: 2.0.6
  eni_utils:
    git:
      url: https://github.com/eniware-systems/eni_utils.git
      ref: 2.0.3
  eni_config:
    git:
      url: https://github.com/eniware-systems/eni_config.git
      ref: 2.0.6
  
  oauth2: ^2.0.3
  url_launcher: ^6.3.2
  window_manager: ^0.5.1
  universal_html: ^2.2.4
  flutter_secure_storage: ^9.2.4
  async: ^2.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  assets:
    - callback.html
