name: eni_auth
description: "Eniware authentication services"
version: 2.0.2
homepage: https://eniware-systems.de
publish_to: https://gitea.eniware-systems.de/api/packages/eni-flutter/pub

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter

  eni_svc:
    hosted: https://gitea.eniware-systems.de/api/packages/eni-flutter/pub
    version: ^2.0.4
  eni_utils:
    hosted: https://gitea.eniware-systems.de/api/packages/eni-flutter/pub
    version: ^2.0.1
  eni_config:
    hosted: https://gitea.eniware-systems.de/api/packages/eni-flutter/pub
    version: ^2.0.3
  
  oauth2: ^2.0.2
  url_launcher: ^6.2.6
  window_manager: ^0.3.8
  universal_html: ^2.2.4
  flutter_secure_storage: ^9.0.0
  async: ^2.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  assets:
    - callback.html
